services:
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=application
    restart: always

  application:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    environment:
      - DATABASE_DSN=postgresql://postgres:password@applications-db:5432/applications
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    command: sh -c "alembic upgrade head && uvicorn --host 0.0.0.0 --port 8000 src.main:app"
    restart: always

volumes:
  app-db-data: